// One-off vendoring: copies browser libraries and fonts into public/ and bundles the
// in-browser runner shims. Outputs are committed, so the app itself has no build step.
//   npm run build:vendor
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { LANGUAGES } from '../public/js/languages.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const nm = (p) => join(root, 'node_modules', p);
const pub = (p) => join(root, 'public', p);
for (const d of ['vendor', 'fonts', 'sandbox', 'css']) mkdirSync(pub(d), { recursive: true });

// 1) Prism — core + every language in public/js/languages.js (the one list), each after the grammars it extends.
//    Manual mode: it never touches the DOM itself.
const deps = JSON.parse(readFileSync(nm('prismjs/components.json'), 'utf8')).languages;
const langs = ['core'];
const add = (id) => {
  if (langs.includes(id)) return;
  if (!deps[id]) throw new Error(`languages.js asks for the Prism grammar "${id}", which this Prism version does not have`);
  for (const need of [].concat(deps[id].require || [])) add(need);
  langs.push(id);
};
for (const l of Object.values(LANGUAGES)) if (l.prism) add(l.prism);
const prism =
  'window.Prism=window.Prism||{};window.Prism.manual=true;window.Prism.disableWorkerMessageHandler=true;\n' +
  langs.map((l) => readFileSync(nm(`prismjs/components/prism-${l}.min.js`), 'utf8')).join('\n');
writeFileSync(pub('vendor/prism.js'), prism);

// 2) markdown-it (UMD → global `markdownit`)
copyFileSync(nm('markdown-it/dist/browser/markdown-it.umd.min.js'), pub('vendor/markdown-it.js'));

// 3) Fonts (latin subset, variable) + @font-face sheet
const fonts = [
  ['@fontsource-variable/newsreader/files/newsreader-latin-opsz-normal.woff2', 'newsreader.woff2'],
  ['@fontsource-variable/newsreader/files/newsreader-latin-wght-italic.woff2', 'newsreader-italic.woff2'],
  ['@fontsource-variable/inter/files/inter-latin-wght-normal.woff2', 'inter.woff2'],
  ['@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2', 'jetbrains-mono.woff2'],
];
for (const [src, dst] of fonts) copyFileSync(nm(src), pub(`fonts/${dst}`));
writeFileSync(
  pub('css/fonts.css'),
  `/* generated by tools/build-vendor.mjs — latin subsets, variable axes */
@font-face{font-family:"Newsreader";font-style:normal;font-weight:200 800;font-display:swap;src:url(/fonts/newsreader.woff2) format("woff2")}
@font-face{font-family:"Newsreader";font-style:italic;font-weight:200 800;font-display:swap;src:url(/fonts/newsreader-italic.woff2) format("woff2")}
@font-face{font-family:"Inter";font-style:normal;font-weight:100 900;font-display:swap;src:url(/fonts/inter.woff2) format("woff2")}
@font-face{font-family:"JetBrains Mono";font-style:normal;font-weight:100 800;font-display:swap;src:url(/fonts/jetbrains-mono.woff2) format("woff2")}
@font-face{font-family:"Inter Fallback";src:local("Arial");size-adjust:107.12%;ascent-override:90.44%;descent-override:22.52%;line-gap-override:0%}
`,
);

// 4) Sandbox shims: bundle the worker runtime to one script, wrapped as a string constant.
const result = await build({
  entryPoints: [join(root, 'tools/shims/runtime.mjs')],
  bundle: true,
  write: false,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  minify: true,
  legalComments: 'none',
  define: { global: 'globalThis' },
  logLevel: 'warning',
});
const code = result.outputFiles[0].text;
writeFileSync(pub('sandbox/shims-src.js'), `self.__SHIMS_SRC=${JSON.stringify(code)};\n`);

const kb = (n) => (n / 1024).toFixed(1) + ' KB';
console.log(`prism ${kb(prism.length)} · shims ${kb(code.length)} · fonts ${fonts.length} files`);
